stages:
  - build
  - test
  - sonarqube

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Directory for SonarQube analysis data
  GIT_DEPTH: "0" # Ensure full Git history is available for analysis

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .sonar/cache

sonarqube-analysis:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  stage: sonarqube
  script:
    - sonar-scanner
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
  tags:
    - mac
    - ios
    - sonar
  variables:
    SONAR_TOKEN: "${SONAR_TOKEN}"
  artifacts:
    paths:
      - .sonar/cache
  allow_failure: false
